// 전임자 인수인계 '연간 점검·선임 캘린더' 엑셀에서 옮긴 초기 데이터 (2026-07)
// months가 빈 배열이면 수시·조건부 업무 (달력 칸 없음)
export const WORK_SEED = [
  { area: '전기', title: '전기설비 직무고시 점검(본사)', cycle: '월1~6회', owner: '전기안전관리자', evidence: '점검결과 기록표', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: false },
  { area: '전기', title: '전기설비 점검(평택·오산)', cycle: '월1~2회', owner: '전기안전관리자', evidence: '점검결과 기록표', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: false },
  { area: '전기', title: '적외선 열화상 측정', cycle: '분기', owner: '전기안전관리자', evidence: '열화상 측정기록표', months: [3, 6, 9, 12], risk: false },
  { area: '전기', title: '전기 정기검사(법정)', cycle: '검사주기', owner: '한국전기안전공사', evidence: '정기검사 확인서', months: [2], risk: false },
  { area: '기계', title: '기계설비 성능점검', cycle: '연1회', owner: '(주)신아엔지니어링', evidence: '성능점검 결과보고서', months: [4], risk: true },
  { area: '기계', title: '기계설비 유지관리 점검', cycle: '월', owner: '유지관리자/외주', evidence: '세부 점검표', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: false },
  { area: '정보통신', title: '유지보수관리자 선임', cycle: '선임(기한 26.01.19)', owner: '(선임/위탁)', evidence: '선임 증빙', months: [1], risk: true },
  { area: '정보통신', title: '정보통신설비 성능점검', cycle: '연1회', owner: '위탁업체', evidence: '성능점검 결과', months: [7], risk: false },
  { area: '소방', title: '소방안전관리자 업무기록', cycle: '월', owner: '소방안전관리자', evidence: '업무 수행기록표', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: false },
  { area: '소방', title: '작동/종합점검', cycle: '연1회', owner: '소방시설관리업체', evidence: '점검 결과보고서', months: [6], risk: false },
  { area: '소방', title: '소방훈련·교육', cycle: '연1회 이상', owner: '소방안전관리자', evidence: '실시 결과기록부', months: [6, 12], risk: false },
  { area: '소방', title: '자위소방대 조직도 갱신', cycle: '연1회', owner: '소방안전관리자', evidence: '조직도', months: [12], risk: false },
  { area: '소방', title: '기숙사 소방 패트롤', cycle: '수시', owner: '소방안전관리자', evidence: '패트롤 보고서', months: [8], risk: false },
  { area: '산업안전', title: '안전보건교육', cycle: '정기', owner: '안전보건담당', evidence: '교육일지·서명지', months: [2, 5, 8, 11], risk: false },
  { area: '산업안전', title: '유해위험방지계획서 관리', cycle: '설비변경 시', owner: '안전보건담당', evidence: '확인결과통지서', months: [], risk: false },
  { area: '산업안전', title: 'MSDS 최신화·게시', cycle: '물질변경 시', owner: '안전보건담당', evidence: 'MSDS', months: [], risk: false },
  { area: '전산', title: '서버/네트워크 유지보수', cycle: '월1회 방문', owner: 'ADDITS', evidence: '유지보수 보고', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: true },
  { area: '전산', title: 'UPS 점검·교체 검토', cycle: '연/수시', owner: 'ADDITS/서버메이트', evidence: '견적·점검서', months: [], risk: false },
  { area: '전산', title: '정보보안 DB세이퍼 점검', cycle: '분기', owner: '외주', evidence: '정기점검 확인서', months: [3, 6, 9, 12], risk: false },
  { area: '전산', title: '백업 결과 결재', cycle: '주간/월', owner: '전산담당', evidence: '백업 결과표', months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], risk: false },
  { area: '경영', title: '차년도 사업계획 수립', cycle: '연1회', owner: '시설전산팀', evidence: '사업계획서', months: [11, 12], risk: false },
  { area: '인증', title: 'ISO 14001/9001 사후심사', cycle: '연1회', owner: '인증기관', evidence: '인증서', months: [], risk: false },
]
